services:
  - type: web
    name: smart-recipe-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build:backend
    startCommand: npm run start --workspace=apps/backend
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        value: https://sqsovisrdvgaeyxlxarf.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxc292aXNyZHZnYWV5eGx4YXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODQyMTgsImV4cCI6MjA2NTA2MDIxOH0.PhsAW3Zv3XGDzZElk46Rt6CAa1V4pd7o8TtuW4M8MhM
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_CLOUD_PROJECT_ID
        sync: false
      - key: CORS_ORIGIN
        value: https://smart-recipe-frontend.vercel.app